version: '3.8'
services:
  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672" 
  consumer:
    build: ./consumer
    container_name: consumer
    ports:
      - "8080:8080"
    volumes:
      - ./consumer:/app
    depends_on:
      - rabbitmq
  producer:
    build: ./producer
    container_name: producer
    ports:
      - "8080:8080"
    volumes:
      - ./producer:/app
    depends_on:
      - rabbitmq
  sender:
    build: ./sender
    container_name: sender
    ports:
      - "8080:8080"
    volumes:
      - ./sender:/app
    depends_on:
      - rabbitmq
  receiver:
    build: ./receiver
    container_name: receiver
    ports:
      - "8081:8081"
    volumes:
      - ./receiver:/app
    depends_on:
      - sender
      - rabbitmq